name : python application 

on:
  push:
      branches: ["main"]

jobs:
 build:
  runs-on: ubuntu-latest

 steps:
    - run: ls 
    - run: pwd
    - run: git4
    - name: list
      run:ls
                                                          
